### ISSUE TITLE
Project Topic

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/Algs_Term_Project#1]
We need to choose a topic! So far we have discussed the broad topics of:
- Cryptography / Encryption
- Computational Geometry

A couple other fun things might be:
- file compression
- error detection / correction

**Comment by JoshMusick** [comment]
I spoke to my manager, and there may be an interesting problem / algorithm we could look at and analyze.  It has to do with how to efficiently ray-cast against multiple polygons at a time, for the generation of a reflection / surface shape, in real time.  The algorithm currently being used only considers the central axis of a beam, and therefore only reflects off of a single surface / polygon, but this limitation is mostly due to performance.  

I will get more info in the next couple of days. I'll keep you both posted.  

I'm not opposed to doing something else, just wanted to throw out a potential idea.

Josh

**Comment by jtautry** [comment]
I think encryption or compression as a broad topic would be interesting.  I would prefer to stay away from geometry or graphics related topics.

**Comment by ericaddison** [comment]
Hi guys,

As we JUST discussed (like, just now), we have identified a potential topic of audio compression algorithms. The project might address some of the following points:
- comparison of several formats (ogg, mp3, mp4, wav, etc), e.g. performance, quality, compression ratio, etc.
- lossy vs lossless compression
- deep analysis of a single format

As backup ideas, this could be applied just as well to image compression (jpeg, gif, png, etc), or focus on lossless file compression (i.e. zipped files). 

Before we talk again, we agreed to take a look to make sure we still think this is a suitable domain for a project. A high level perusal of audio formats and algorithms should give us an idea of whether there's enough for a good project.

Thanks guys!
